name: test_and_lint

on:
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches:
      - master

jobs:
  test_and_lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Check style, Linters, Tests
        run: make check
